name: AccuKnox Scan Workflow

on:
  push:
    branches:
      - main

jobs:
  accuknox-cicd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Build Docker image
        run: |
          IMAGE_NAME="github-action-test"
          IMAGE_TAG="latest"
          docker build -t "$IMAGE_NAME:$IMAGE_TAG" .
          echo "Successfully built Docker image: $IMAGE_NAME:$IMAGE_TAG"

      - name: Run Accuknox Container
        uses: accuknox/container-scan-action@v1.1.0
        with:
          endpoint: ${{ secrets.ACCUKNOX_ENDPOINT }}
          token: ${{ secrets.ACCUKNOX_TOKEN }}
          label: ${{ secrets.ACCUKNOX_LABEL }}
          image: "github-action-test"
          tag: "latest"
